// Code generated by protoc-gen-go.
// source: COR-Framework/protocol/message.proto
// DO NOT EDIT!

/*
Package cor is a generated protocol buffer package.

It is generated from these files:
	COR-Framework/protocol/message.proto

It has these top-level messages:
	CORMessage
*/
package cor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CORMessage struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CORMessage) Reset()                    { *m = CORMessage{} }
func (m *CORMessage) String() string            { return proto.CompactTextString(m) }
func (*CORMessage) ProtoMessage()               {}
func (*CORMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CORMessage) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CORMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CORMessage)(nil), "cor.CORMessage")
}

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x71, 0xf6, 0x0f, 0xd2,
	0x75, 0x2b, 0x4a, 0xcc, 0x4d, 0x2d, 0xcf, 0x2f, 0xca, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f,
	0xce, 0xcf, 0xd1, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03, 0x0b, 0x08, 0x31, 0x27,
	0xe7, 0x17, 0x29, 0x69, 0x70, 0x71, 0x01, 0x15, 0xfb, 0x42, 0x24, 0x84, 0x78, 0xb8, 0x58, 0x4a,
	0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x98, 0x34, 0x38, 0x41, 0xbc, 0x94, 0xc4, 0x92, 0x44, 0x09,
	0x26, 0x20, 0x8f, 0x07, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xbe, 0x08, 0xde, 0x55, 0x00, 0x00,
	0x00,
}
